### PR TITLE
Integrate calibration and parameters from liboptv

### PR DESCRIPTION
**Pull request by yosefm**
* Also required dragging in vec_utils.
* Alex, there are some of your commits here which aparrently aren't in master yet, please take a look to see that their ok.
* I'm terribly sorry for the big hunk. I haven't merged any of my changes for a long time, and this is the smallest bit I've been able to break out of my optv integration work.
* Test pass on my side as well as rudimentary usage, but until I bring it up to date with my full integration branch, there may be pitfalls, so if you please test with real data.
* Also some removals in orientation.c - they are old on my side but still exist on master. Nothing uses these functions and it was easier to include the removal than to break it out. Again, please excuse the heap for this time.

### CODE REVIEW

**Comment by alexlib** [comment]
Seems to be a bug: https://github.com/yosefm/openptv-python/blob/integ_cal_param/src_c/orientation.c#L726

we try to allocate 5000 values in the matrix set on 1800 only. It fails on Mac with segfault

**Comment by yosefm** [comment]
Yes, when I did the merge I accidentally reverted the expansion to 10000 values you gave it in one of your commits. Fix coming. Although I do wonder why 10000 places but 5000 in the loop.

**Comment by alexlib** [comment]
maybe we shall leave first go through openptv-python and only fix the bugs. is it possible/reasonable ?

**Comment by yosefm** [comment]
What do you mean by 'leave first go'?

**Comment by yosefm** [comment]
I want to do this too. However, it creates problems in two places.

1. You don't get to benefit from work I already did when you make new submissions to liboptv. But this can be worked around by checking for differences with my bitbucket repo before starting something.

2. I still need to use parts of pyptv in my code because they aren't in liboptv yet, but using both together becomes impossible in the same executable. That's why I keep my branch of ongoing integration. And in that branch I don't benefit from your bug-fixes like PR #25 that started this.

3. How do we know that liboptv achieves its purpose unless we actually use it? Unit tests are nice but they are nothing like real-world usage. For the calibration parts I have another test-bed (but it's only me), but what about other parts?

I think the confusion will subside with the next PRs here, as divergence is reduced. But if you prefer to keep it separate, I'll leave this code in a branch and incorporate your bugfixes only locally as needed. It's not very crucial to merge right now.

**Comment by alexlib** [comment]
ok. let's continue. i'll try to merge all this PR as is and test it on the data

**Comment by yosefm** [comment]
This one was agains the current OpenPTV master.

**Comment by yosefm** [comment]
What is the reason for making 10,000-member arrays but running the loop to 5000 only?

**Comment by alexlib** [comment]
the size of the matrix X and vector y would be n, which is twice larger than the number of points, cause we solve one line for ```x``` and one line for ```y``` for each point in nfix 
i guess the reasonable solution is to run the loop for 10000. in the new orient we anyhow allocate memory precisely for nfix * 2 so there would be no question about it.

**Comment by alexlib** [comment]
I do not think that we often have 5000 calibration points to analyse. I think this was one particular case from Zurich that did some scanning or multiplane calibration. Otherwise, we speak of hundreds at most.

**Comment by alexlib** [comment]
after we merged to liboptv master, I cannot compile/install the openptv-python from this branch. The error is:

ptv1.c:244:10: fatal error: 'optv/parameters.h' file not found
#include "optv/parameters.h"

**Comment by yosefm** [comment]
Then you don't have liboptv in your include path, or else it's finding an older liboptv without parameters.h.

**Comment by alexlib** [comment]
you're right. i had to delete also all the /usr/local/include/optv and /usr/local/lib/liboptv.dylib and also run python setup.py clean to get including and linking correctly.

**Comment by alexlib** [comment]
recommend to merge and tag this openptv-python version. from now and on we could probably sync better the progress in both liboptv and openptv-python?

**Comment by yosefm** [comment]
Alex, I tried to recreate the pairs crash you mentioned with my data and with test_cavity and couldn't so I'll merge, and if we hit that bug again we'll look for it harder.

**Pull request merged**
