### PR TITLE
More liboptv integration

### PR DESCRIPTION
**Pull request by yosefm**
I'm sorry that this is another long one, but we are getting closer. The last commits here before the merge are from 9/2015 so we're getting up to date.

This time the following liboptv features are integrated: lsqadj, ray tracing, trafo, the first image-processing features, more use of liboptv parameters reading. 

There is some cleaning up interleaved, and globals removed because no longer needed in liboptv.

### CODE REVIEW

**Comment by alexlib** [comment]
there is some problem with orientation.c, e.g. https://github.com/yosefm/openptv-python/blob/2f62c7f29a7f384f4271a4d7b5b6de4e0cf2c71d/src_c/orientation.c#L420 the eval_ori_v2 is called with ```db_scale``` as a first argument, but the function itself waits for the Calibration as the first input.

**Comment by yosefm** [comment]
Luckily this is another thing fixed higher up my tree. Please try now with the cherry-picked fix.

**Comment by alexlib** [comment]
still not good. see the patch here https://www.dropbox.com/s/erdooemt8unzuuw/patch.diff?dl=0

moreover, there is some new segfault 11 (memory of file access) I get when I run 

```
Alexs-MacBook-Pro-2:pyptv_gui alex$ python pyptv_batch.py ../../test_cavity/ 10000 10004
software_path= /Users/alex/Documents/OpenPTV/openptv-python/pyptv_gui
exp_path= /Users/alex/Documents/OpenPTV/test_cavity
/Users/alex/Documents/OpenPTV/test_cavity

 Multimedia Particle Positioning and Tracking Software 

Starting sequence action

Object volume is scanned in 19 slices!

zdim: 80.000000, max: 40.000000, min: -40.000000, st: 4.210526
1
('Setting image: ', 'img/cam1.10000')
('Setting image: ', 'img/cam2.10000')
('Setting image: ', 'img/cam3.10000')
('Setting image: ', 'img/cam4.10000')

Highpass switched on

 Peak fitting version is 3
inside peak_fit_new
opened file ?3#assigned file header 2009596136inside peak_fit_new
opened file ?3#assigned file header 2009596136inside peak_fit_new
opened file ?3#assigned file header 2009596136inside peak_fit_new
opened file ?3#assigned file header 2009596136pix.x01=1036.034645
pix.y01=18.450813


Transformation to metric coordinates

Init multimedia displacement LUTs
Establishing correspondences  0 - 1
Establishing correspondences  0 - 2
Establishing correspondences  0 - 3
Establishing correspondences  1 - 2
Establishing correspondences  1 - 3
Establishing correspondences  2 - 3
72 consistent quadruplets, 
Establishing correspondences
Search consistent triplets 
72 consistent quadruplets, 497 triplets 
Search pairs72 quadruplets (red), 497 triplets (green) and 0 unambigous pairs
unidentified objects = 726
Segmentation fault: 11
```

**Comment by yosefm** [comment]
Had to cherry-pick two later commits to fix the segfaults, but it should be ok now.
BTW - these are all errors that would have been caught by the compiler if we had proper function prototypes instead of globals.h, but ok, we're slowly making it so.

**Comment by yosefm** [comment]
Now tracking segfaults, possibly because of two versions of img_coord or something like that. Will investigate later.

**Comment by yosefm** [comment]
For the life of me, I have no idea why this worked before. I think I never actually ran tracking on this particular branch. Anyway, now it works, please test again.

**Comment by alexlib** [comment]
works perfectly. recommend to merge

**Comment by alexlib** [comment]
all works but the shaking (orientation from particles) for scene17. I start with the cal_3d or cal_mp ori files, I run the sequence in scene17 from 1587 to 1687, set number of particles to 1000 and number of frames to 100 (so it reads all the quadruplets and all the frames, about 277 particles) and then after 2-3 iterations it fails with segfault or runs into NaNs solution. When I try to debug and print fix[].x,y,z, I get zeros instead of 3d points. I cannot find in the prepare_eval_shake or in read_frame place where fix[] is set for the shaking.

**Comment by yosefm** [comment]
The shaking bug dates back to 40ad04a3e3a0, it is not related to this PR. I suggest to merge this and I'll do a separate PR to fix it. See also Issue 27.

**Comment by alexlib** [comment]
agree. let's merge

**Comment by yosefm** [comment]
For the shaking fix:
https://github.com/OpenPTV/openptv-python/pull/29

**Pull request merged**
